// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backtests.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimBacktestRun = `-- name: ClaimBacktestRun :one
UPDATE backtest_runs
SET status = 'running',
    started_at = NOW(),
    error = NULL
WHERE id = (
    SELECT id FROM backtest_runs
    WHERE status = 'queued'
    ORDER BY (sweep_id IS NOT NULL), created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, user_id, strategy_id, spec, symbol_id, timeframe, start_date, end_date, capital_cents, status, metrics, error, created_at, started_at, finished_at, max_positions, sweep_id, params, point, fold, phase
`

func (q *Queries) ClaimBacktestRun(ctx context.Context) (BacktestRun, error) {
	row := q.db.QueryRow(ctx, claimBacktestRun)
	var i BacktestRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StrategyID,
		&i.Spec,
		&i.SymbolID,
		&i.Timeframe,
		&i.StartDate,
		&i.EndDate,
		&i.CapitalCents,
		&i.Status,
		&i.Metrics,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.MaxPositions,
		&i.SweepID,
		&i.Params,
		&i.Point,
		&i.Fold,
		&i.Phase,
	)
	return i, err
}

const countActiveBacktestRuns = `-- name: CountActiveBacktestRuns :one
SELECT COUNT(*) FROM backtest_runs
WHERE user_id = $1 AND sweep_id IS NULL AND status IN ('queued', 'running')
`

func (q *Queries) CountActiveBacktestRuns(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBacktestRuns, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBacktestEquity = `-- name: CountBacktestEquity :one
SELECT COUNT(*) FROM backtest_equity WHERE run_id = $1
`

func (q *Queries) CountBacktestEquity(ctx context.Context, runID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBacktestEquity, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBacktestRunsByStatus = `-- name: CountBacktestRunsByStatus :many
SELECT status, COUNT(*) AS runs FROM backtest_runs
WHERE status IN ('queued', 'running')
GROUP BY status
`

type CountBacktestRunsByStatusRow struct {
	Status string `json:"status"`
	Runs   int64  `json:"runs"`
}

func (q *Queries) CountBacktestRunsByStatus(ctx context.Context) ([]CountBacktestRunsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countBacktestRunsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountBacktestRunsByStatusRow{}
	for rows.Next() {
		var i CountBacktestRunsByStatusRow
		if err := rows.Scan(&i.Status, &i.Runs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBacktestSymbolEquity = `-- name: CountBacktestSymbolEquity :one
SELECT COUNT(*) FROM backtest_symbol_equity WHERE run_id = $1
`

func (q *Queries) CountBacktestSymbolEquity(ctx context.Context, runID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBacktestSymbolEquity, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateBacktestEquityParams struct {
	RunID       uuid.UUID `json:"run_id"`
	Ts          time.Time `json:"ts"`
	EquityCents int64     `json:"equity_cents"`
	HoldCents   *int64    `json:"hold_cents"`
	IndexCents  *int64    `json:"index_cents"`
}

const createBacktestRun = `-- name: CreateBacktestRun :one
INSERT INTO backtest_runs (
    user_id, strategy_id, spec, symbol_id, timeframe,
    start_date, end_date, capital_cents, max_positions, status,
    sweep_id, params, point, fold, phase
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, 'queued',
    $10, $11, $12, $13, $14
)
RETURNING id, user_id, strategy_id, spec, symbol_id, timeframe, start_date, end_date, capital_cents, status, metrics, error, created_at, started_at, finished_at, max_positions, sweep_id, params, point, fold, phase
`

type CreateBacktestRunParams struct {
	UserID       uuid.UUID  `json:"user_id"`
	StrategyID   uuid.UUID  `json:"strategy_id"`
	Spec         []byte     `json:"spec"`
	SymbolID     int64      `json:"symbol_id"`
	Timeframe    string     `json:"timeframe"`
	StartDate    time.Time  `json:"start_date"`
	EndDate      time.Time  `json:"end_date"`
	CapitalCents int64      `json:"capital_cents"`
	MaxPositions int32      `json:"max_positions"`
	SweepID      *uuid.UUID `json:"sweep_id"`
	Params       []byte     `json:"params"`
	Point        *int32     `json:"point"`
	Fold         *int32     `json:"fold"`
	Phase        *string    `json:"phase"`
}

func (q *Queries) CreateBacktestRun(ctx context.Context, arg CreateBacktestRunParams) (BacktestRun, error) {
	row := q.db.QueryRow(ctx, createBacktestRun,
		arg.UserID,
		arg.StrategyID,
		arg.Spec,
		arg.SymbolID,
		arg.Timeframe,
		arg.StartDate,
		arg.EndDate,
		arg.CapitalCents,
		arg.MaxPositions,
		arg.SweepID,
		arg.Params,
		arg.Point,
		arg.Fold,
		arg.Phase,
	)
	var i BacktestRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StrategyID,
		&i.Spec,
		&i.SymbolID,
		&i.Timeframe,
		&i.StartDate,
		&i.EndDate,
		&i.CapitalCents,
		&i.Status,
		&i.Metrics,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.MaxPositions,
		&i.SweepID,
		&i.Params,
		&i.Point,
		&i.Fold,
		&i.Phase,
	)
	return i, err
}

type CreateBacktestRunSymbolsParams struct {
	RunID    uuid.UUID `json:"run_id"`
	Ord      int32     `json:"ord"`
	SymbolID int64     `json:"symbol_id"`
}

type CreateBacktestSymbolEquityParams struct {
	RunID       uuid.UUID `json:"run_id"`
	SymbolID    int64     `json:"symbol_id"`
	Ts          time.Time `json:"ts"`
	EquityCents int64     `json:"equity_cents"`
}

type CreateBacktestTradesParams struct {
	RunID          uuid.UUID  `json:"run_id"`
	Seq            int32      `json:"seq"`
	SymbolID       int64      `json:"symbol_id"`
	Side           string     `json:"side"`
	Qty            int64      `json:"qty"`
	EntryTs        time.Time  `json:"entry_ts"`
	EntryPrice     float64    `json:"entry_price"`
	ExitTs         *time.Time `json:"exit_ts"`
	ExitPrice      *float64   `json:"exit_price"`
	PnlCents       *int64     `json:"pnl_cents"`
	FeesCents      int64      `json:"fees_cents"`
	DividendsCents int64      `json:"dividends_cents"`
	BorrowCents    int64      `json:"borrow_cents"`
	SplitCashCents int64      `json:"split_cash_cents"`
	ExitReason     *string    `json:"exit_reason"`
}

const failBacktestRun = `-- name: FailBacktestRun :exec
UPDATE backtest_runs
SET status = 'error',
    error = $2,
    finished_at = NOW()
WHERE id = $1
`

type FailBacktestRunParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) FailBacktestRun(ctx context.Context, arg FailBacktestRunParams) error {
	_, err := q.db.Exec(ctx, failBacktestRun, arg.ID, arg.Error)
	return err
}

const finishBacktestRun = `-- name: FinishBacktestRun :exec
UPDATE backtest_runs
SET status = 'done',
    metrics = $2,
    error = NULL,
    finished_at = NOW()
WHERE id = $1
`

type FinishBacktestRunParams struct {
	ID      uuid.UUID `json:"id"`
	Metrics []byte    `json:"metrics"`
}

func (q *Queries) FinishBacktestRun(ctx context.Context, arg FinishBacktestRunParams) error {
	_, err := q.db.Exec(ctx, finishBacktestRun, arg.ID, arg.Metrics)
	return err
}

const getBacktestRun = `-- name: GetBacktestRun :one
SELECT r.id, r.user_id, r.strategy_id, r.spec, r.symbol_id, r.timeframe, r.start_date, r.end_date, r.capital_cents, r.status, r.metrics, r.error, r.created_at, r.started_at, r.finished_at, r.max_positions, r.sweep_id, r.params, r.point, r.fold, r.phase, s.ticker
FROM backtest_runs r
JOIN symbols s ON s.id = r.symbol_id
WHERE r.id = $1 AND r.user_id = $2
`

type GetBacktestRunParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetBacktestRunRow struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	StrategyID   uuid.UUID  `json:"strategy_id"`
	Spec         []byte     `json:"spec"`
	SymbolID     int64      `json:"symbol_id"`
	Timeframe    string     `json:"timeframe"`
	StartDate    time.Time  `json:"start_date"`
	EndDate      time.Time  `json:"end_date"`
	CapitalCents int64      `json:"capital_cents"`
	Status       string     `json:"status"`
	Metrics      []byte     `json:"metrics"`
	Error        *string    `json:"error"`
	CreatedAt    time.Time  `json:"created_at"`
	StartedAt    *time.Time `json:"started_at"`
	FinishedAt   *time.Time `json:"finished_at"`
	MaxPositions int32      `json:"max_positions"`
	SweepID      *uuid.UUID `json:"sweep_id"`
	Params       []byte     `json:"params"`
	Point        *int32     `json:"point"`
	Fold         *int32     `json:"fold"`
	Phase        *string    `json:"phase"`
	Ticker       string     `json:"ticker"`
}

func (q *Queries) GetBacktestRun(ctx context.Context, arg GetBacktestRunParams) (GetBacktestRunRow, error) {
	row := q.db.QueryRow(ctx, getBacktestRun, arg.ID, arg.UserID)
	var i GetBacktestRunRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StrategyID,
		&i.Spec,
		&i.SymbolID,
		&i.Timeframe,
		&i.StartDate,
		&i.EndDate,
		&i.CapitalCents,
		&i.Status,
		&i.Metrics,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.MaxPositions,
		&i.SweepID,
		&i.Params,
		&i.Point,
		&i.Fold,
		&i.Phase,
		&i.Ticker,
	)
	return i, err
}

const listBacktestEquity = `-- name: ListBacktestEquity :many
SELECT ts, equity_cents, hold_cents, index_cents
FROM (
    SELECT ts, equity_cents, hold_cents, index_cents,
           ROW_NUMBER() OVER (ORDER BY ts) AS n,
           COUNT(*) OVER () AS total
    FROM backtest_equity
    WHERE run_id = $1
) points
WHERE (n - 1) % GREATEST((total + $2::bigint - 1) / $2::bigint, 1) = 0 OR n = total
ORDER BY ts
`

type ListBacktestEquityParams struct {
	RunID   uuid.UUID `json:"run_id"`
	Column2 int64     `json:"column_2"`
}

type ListBacktestEquityRow struct {
	Ts          time.Time `json:"ts"`
	EquityCents int64     `json:"equity_cents"`
	HoldCents   *int64    `json:"hold_cents"`
	IndexCents  *int64    `json:"index_cents"`
}

func (q *Queries) ListBacktestEquity(ctx context.Context, arg ListBacktestEquityParams) ([]ListBacktestEquityRow, error) {
	rows, err := q.db.Query(ctx, listBacktestEquity, arg.RunID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBacktestEquityRow{}
	for rows.Next() {
		var i ListBacktestEquityRow
		if err := rows.Scan(
			&i.Ts,
			&i.EquityCents,
			&i.HoldCents,
			&i.IndexCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBacktestRunSymbols = `-- name: ListBacktestRunSymbols :many
SELECT rs.ord, s.id, s.ticker, s.kind, s.lot_size, s.tick_size
FROM backtest_run_symbols rs
JOIN symbols s ON s.id = rs.symbol_id
WHERE rs.run_id = $1
ORDER BY rs.ord
`

type ListBacktestRunSymbolsRow struct {
	Ord      int32   `json:"ord"`
	ID       int64   `json:"id"`
	Ticker   string  `json:"ticker"`
	Kind     string  `json:"kind"`
	LotSize  int32   `json:"lot_size"`
	TickSize float64 `json:"tick_size"`
}

func (q *Queries) ListBacktestRunSymbols(ctx context.Context, runID uuid.UUID) ([]ListBacktestRunSymbolsRow, error) {
	rows, err := q.db.Query(ctx, listBacktestRunSymbols, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBacktestRunSymbolsRow{}
	for rows.Next() {
		var i ListBacktestRunSymbolsRow
		if err := rows.Scan(
			&i.Ord,
			&i.ID,
			&i.Ticker,
			&i.Kind,
			&i.LotSize,
			&i.TickSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBacktestRunTickers = `-- name: ListBacktestRunTickers :many
SELECT rs.run_id, rs.ord, s.ticker
FROM backtest_run_symbols rs
JOIN symbols s ON s.id = rs.symbol_id
WHERE rs.run_id = ANY($1::uuid[])
ORDER BY rs.run_id, rs.ord
`

type ListBacktestRunTickersRow struct {
	RunID  uuid.UUID `json:"run_id"`
	Ord    int32     `json:"ord"`
	Ticker string    `json:"ticker"`
}

func (q *Queries) ListBacktestRunTickers(ctx context.Context, dollar_1 []uuid.UUID) ([]ListBacktestRunTickersRow, error) {
	rows, err := q.db.Query(ctx, listBacktestRunTickers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBacktestRunTickersRow{}
	for rows.Next() {
		var i ListBacktestRunTickersRow
		if err := rows.Scan(&i.RunID, &i.Ord, &i.Ticker); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBacktestRuns = `-- name: ListBacktestRuns :many
SELECT r.id, r.user_id, r.strategy_id, r.spec, r.symbol_id, r.timeframe, r.start_date, r.end_date, r.capital_cents, r.status, r.metrics, r.error, r.created_at, r.started_at, r.finished_at, r.max_positions, r.sweep_id, r.params, r.point, r.fold, r.phase, s.ticker
FROM backtest_runs r
JOIN symbols s ON s.id = r.symbol_id
WHERE r.user_id = $1 AND r.sweep_id IS NULL
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListBacktestRunsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListBacktestRunsRow struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	StrategyID   uuid.UUID  `json:"strategy_id"`
	Spec         []byte     `json:"spec"`
	SymbolID     int64      `json:"symbol_id"`
	Timeframe    string     `json:"timeframe"`
	StartDate    time.Time  `json:"start_date"`
	EndDate      time.Time  `json:"end_date"`
	CapitalCents int64      `json:"capital_cents"`
	Status       string     `json:"status"`
	Metrics      []byte     `json:"metrics"`
	Error        *string    `json:"error"`
	CreatedAt    time.Time  `json:"created_at"`
	StartedAt    *time.Time `json:"started_at"`
	FinishedAt   *time.Time `json:"finished_at"`
	MaxPositions int32      `json:"max_positions"`
	SweepID      *uuid.UUID `json:"sweep_id"`
	Params       []byte     `json:"params"`
	Point        *int32     `json:"point"`
	Fold         *int32     `json:"fold"`
	Phase        *string    `json:"phase"`
	Ticker       string     `json:"ticker"`
}

func (q *Queries) ListBacktestRuns(ctx context.Context, arg ListBacktestRunsParams) ([]ListBacktestRunsRow, error) {
	rows, err := q.db.Query(ctx, listBacktestRuns, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBacktestRunsRow{}
	for rows.Next() {
		var i ListBacktestRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StrategyID,
			&i.Spec,
			&i.SymbolID,
			&i.Timeframe,
			&i.StartDate,
			&i.EndDate,
			&i.CapitalCents,
			&i.Status,
			&i.Metrics,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.MaxPositions,
			&i.SweepID,
			&i.Params,
			&i.Point,
			&i.Fold,
			&i.Phase,
			&i.Ticker,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBacktestSymbolEquity = `-- name: ListBacktestSymbolEquity :many
SELECT ticker, ts, equity_cents
FROM (
    SELECT s.ticker, se.ts, se.equity_cents,
           ROW_NUMBER() OVER (PARTITION BY se.symbol_id ORDER BY se.ts) AS n,
           COUNT(*) OVER (PARTITION BY se.symbol_id) AS total
    FROM backtest_symbol_equity se
    JOIN symbols s ON s.id = se.symbol_id
    WHERE se.run_id = $1
) points
WHERE (n - 1) % GREATEST((total + $2::bigint - 1) / $2::bigint, 1) = 0 OR n = total
ORDER BY ticker, ts
`

type ListBacktestSymbolEquityParams struct {
	RunID   uuid.UUID `json:"run_id"`
	Column2 int64     `json:"column_2"`
}

type ListBacktestSymbolEquityRow struct {
	Ticker      string    `json:"ticker"`
	Ts          time.Time `json:"ts"`
	EquityCents int64     `json:"equity_cents"`
}

func (q *Queries) ListBacktestSymbolEquity(ctx context.Context, arg ListBacktestSymbolEquityParams) ([]ListBacktestSymbolEquityRow, error) {
	rows, err := q.db.Query(ctx, listBacktestSymbolEquity, arg.RunID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBacktestSymbolEquityRow{}
	for rows.Next() {
		var i ListBacktestSymbolEquityRow
		if err := rows.Scan(&i.Ticker, &i.Ts, &i.EquityCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBacktestTrades = `-- name: ListBacktestTrades :many
SELECT t.seq, s.ticker, t.side, t.qty, t.entry_ts, t.entry_price, t.exit_ts, t.exit_price,
       t.pnl_cents, t.fees_cents, t.dividends_cents, t.borrow_cents, t.split_cash_cents,
       t.exit_reason
FROM backtest_trades t
JOIN symbols s ON s.id = t.symbol_id
WHERE t.run_id = $1
ORDER BY t.seq
`

type ListBacktestTradesRow struct {
	Seq            int32      `json:"seq"`
	Ticker         string     `json:"ticker"`
	Side           string     `json:"side"`
	Qty            int64      `json:"qty"`
	EntryTs        time.Time  `json:"entry_ts"`
	EntryPrice     float64    `json:"entry_price"`
	ExitTs         *time.Time `json:"exit_ts"`
	ExitPrice      *float64   `json:"exit_price"`
	PnlCents       *int64     `json:"pnl_cents"`
	FeesCents      int64      `json:"fees_cents"`
	DividendsCents int64      `json:"dividends_cents"`
	BorrowCents    int64      `json:"borrow_cents"`
	SplitCashCents int64      `json:"split_cash_cents"`
	ExitReason     *string    `json:"exit_reason"`
}

func (q *Queries) ListBacktestTrades(ctx context.Context, runID uuid.UUID) ([]ListBacktestTradesRow, error) {
	rows, err := q.db.Query(ctx, listBacktestTrades, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBacktestTradesRow{}
	for rows.Next() {
		var i ListBacktestTradesRow
		if err := rows.Scan(
			&i.Seq,
			&i.Ticker,
			&i.Side,
			&i.Qty,
			&i.EntryTs,
			&i.EntryPrice,
			&i.ExitTs,
			&i.ExitPrice,
			&i.PnlCents,
			&i.FeesCents,
			&i.DividendsCents,
			&i.BorrowCents,
			&i.SplitCashCents,
			&i.ExitReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueBacktestRun = `-- name: RequeueBacktestRun :exec
UPDATE backtest_runs
SET status = 'queued',
    started_at = NULL
WHERE id = $1 AND status = 'running'
`

func (q *Queries) RequeueBacktestRun(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, requeueBacktestRun, id)
	return err
}

const requeueStaleBacktestRuns = `-- name: RequeueStaleBacktestRuns :execrows
UPDATE backtest_runs
SET status = 'queued',
    started_at = NULL
WHERE status = 'running' AND started_at < $1::timestamptz
`

func (q *Queries) RequeueStaleBacktestRuns(ctx context.Context, dollar_1 time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, requeueStaleBacktestRuns, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
