// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brapi_usage.sql

package database

import (
	"context"
	"time"
)

const listBrapiUsage = `-- name: ListBrapiUsage :many
SELECT day, requests FROM brapi_usage
WHERE day BETWEEN $1 AND $2
ORDER BY day
`

type ListBrapiUsageParams struct {
	Day   time.Time `json:"day"`
	Day_2 time.Time `json:"day_2"`
}

func (q *Queries) ListBrapiUsage(ctx context.Context, arg ListBrapiUsageParams) ([]BrapiUsage, error) {
	rows, err := q.db.Query(ctx, listBrapiUsage, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrapiUsage{}
	for rows.Next() {
		var i BrapiUsage
		if err := rows.Scan(&i.Day, &i.Requests); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordBrapiRequests = `-- name: RecordBrapiRequests :one
INSERT INTO brapi_usage (day, requests)
VALUES ($1, $2)
ON CONFLICT (day) DO UPDATE SET requests = brapi_usage.requests + EXCLUDED.requests
RETURNING day, requests
`

type RecordBrapiRequestsParams struct {
	Day      time.Time `json:"day"`
	Requests int32     `json:"requests"`
}

func (q *Queries) RecordBrapiRequests(ctx context.Context, arg RecordBrapiRequestsParams) (BrapiUsage, error) {
	row := q.db.QueryRow(ctx, recordBrapiRequests, arg.Day, arg.Requests)
	var i BrapiUsage
	err := row.Scan(&i.Day, &i.Requests)
	return i, err
}

const sumBrapiUsage = `-- name: SumBrapiUsage :one
SELECT COALESCE(sum(requests), 0)::bigint AS requests
FROM brapi_usage
WHERE day BETWEEN $1 AND $2
`

type SumBrapiUsageParams struct {
	Day   time.Time `json:"day"`
	Day_2 time.Time `json:"day_2"`
}

func (q *Queries) SumBrapiUsage(ctx context.Context, arg SumBrapiUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumBrapiUsage, arg.Day, arg.Day_2)
	var requests int64
	err := row.Scan(&requests)
	return requests, err
}
