// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candles.sql

package database

import (
	"context"
	"time"
)

const countCandles = `-- name: CountCandles :one
SELECT count(*)
FROM candles
WHERE symbol_id = $1 AND timeframe = $2
`

type CountCandlesParams struct {
	SymbolID  int64  `json:"symbol_id"`
	Timeframe string `json:"timeframe"`
}

func (q *Queries) CountCandles(ctx context.Context, arg CountCandlesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCandles, arg.SymbolID, arg.Timeframe)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCandlesInRange = `-- name: CountCandlesInRange :one
SELECT count(*)
FROM candles
WHERE symbol_id = $1 AND timeframe = $2 AND ts >= $3 AND ts < $4
`

type CountCandlesInRangeParams struct {
	SymbolID  int64     `json:"symbol_id"`
	Timeframe string    `json:"timeframe"`
	Ts        time.Time `json:"ts"`
	Ts_2      time.Time `json:"ts_2"`
}

func (q *Queries) CountCandlesInRange(ctx context.Context, arg CountCandlesInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCandlesInRange,
		arg.SymbolID,
		arg.Timeframe,
		arg.Ts,
		arg.Ts_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const earliestCandle = `-- name: EarliestCandle :one
SELECT ts, open, high, low, close, adj_close, volume
FROM candles
WHERE symbol_id = $1 AND timeframe = $2
ORDER BY ts
LIMIT 1
`

type EarliestCandleParams struct {
	SymbolID  int64  `json:"symbol_id"`
	Timeframe string `json:"timeframe"`
}

type EarliestCandleRow struct {
	Ts       time.Time `json:"ts"`
	Open     float64   `json:"open"`
	High     float64   `json:"high"`
	Low      float64   `json:"low"`
	Close    float64   `json:"close"`
	AdjClose *float64  `json:"adj_close"`
	Volume   int64     `json:"volume"`
}

func (q *Queries) EarliestCandle(ctx context.Context, arg EarliestCandleParams) (EarliestCandleRow, error) {
	row := q.db.QueryRow(ctx, earliestCandle, arg.SymbolID, arg.Timeframe)
	var i EarliestCandleRow
	err := row.Scan(
		&i.Ts,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.AdjClose,
		&i.Volume,
	)
	return i, err
}

const latestCandle = `-- name: LatestCandle :one
SELECT ts, open, high, low, close, adj_close, volume
FROM candles
WHERE symbol_id = $1 AND timeframe = $2
ORDER BY ts DESC
LIMIT 1
`

type LatestCandleParams struct {
	SymbolID  int64  `json:"symbol_id"`
	Timeframe string `json:"timeframe"`
}

type LatestCandleRow struct {
	Ts       time.Time `json:"ts"`
	Open     float64   `json:"open"`
	High     float64   `json:"high"`
	Low      float64   `json:"low"`
	Close    float64   `json:"close"`
	AdjClose *float64  `json:"adj_close"`
	Volume   int64     `json:"volume"`
}

func (q *Queries) LatestCandle(ctx context.Context, arg LatestCandleParams) (LatestCandleRow, error) {
	row := q.db.QueryRow(ctx, latestCandle, arg.SymbolID, arg.Timeframe)
	var i LatestCandleRow
	err := row.Scan(
		&i.Ts,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.AdjClose,
		&i.Volume,
	)
	return i, err
}

const listCandleTimestamps = `-- name: ListCandleTimestamps :many
SELECT ts
FROM candles
WHERE symbol_id = $1 AND timeframe = $2 AND ts >= $3 AND ts < $4
ORDER BY ts
`

type ListCandleTimestampsParams struct {
	SymbolID  int64     `json:"symbol_id"`
	Timeframe string    `json:"timeframe"`
	Ts        time.Time `json:"ts"`
	Ts_2      time.Time `json:"ts_2"`
}

func (q *Queries) ListCandleTimestamps(ctx context.Context, arg ListCandleTimestampsParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, listCandleTimestamps,
		arg.SymbolID,
		arg.Timeframe,
		arg.Ts,
		arg.Ts_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var ts time.Time
		if err := rows.Scan(&ts); err != nil {
			return nil, err
		}
		items = append(items, ts)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandles = `-- name: ListCandles :many
SELECT ts, open, high, low, close, adj_close, volume
FROM candles
WHERE symbol_id = $1 AND timeframe = $2 AND ts >= $3 AND ts < $4
ORDER BY ts
LIMIT $5
`

type ListCandlesParams struct {
	SymbolID  int64     `json:"symbol_id"`
	Timeframe string    `json:"timeframe"`
	Ts        time.Time `json:"ts"`
	Ts_2      time.Time `json:"ts_2"`
	Limit     int32     `json:"limit"`
}

type ListCandlesRow struct {
	Ts       time.Time `json:"ts"`
	Open     float64   `json:"open"`
	High     float64   `json:"high"`
	Low      float64   `json:"low"`
	Close    float64   `json:"close"`
	AdjClose *float64  `json:"adj_close"`
	Volume   int64     `json:"volume"`
}

func (q *Queries) ListCandles(ctx context.Context, arg ListCandlesParams) ([]ListCandlesRow, error) {
	rows, err := q.db.Query(ctx, listCandles,
		arg.SymbolID,
		arg.Timeframe,
		arg.Ts,
		arg.Ts_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCandlesRow{}
	for rows.Next() {
		var i ListCandlesRow
		if err := rows.Scan(
			&i.Ts,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.AdjClose,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandlesDesc = `-- name: ListCandlesDesc :many
SELECT ts, open, high, low, close, adj_close, volume
FROM candles
WHERE symbol_id = $1 AND timeframe = $2 AND ts >= $3 AND ts < $4
ORDER BY ts DESC
LIMIT $5
`

type ListCandlesDescParams struct {
	SymbolID  int64     `json:"symbol_id"`
	Timeframe string    `json:"timeframe"`
	Ts        time.Time `json:"ts"`
	Ts_2      time.Time `json:"ts_2"`
	Limit     int32     `json:"limit"`
}

type ListCandlesDescRow struct {
	Ts       time.Time `json:"ts"`
	Open     float64   `json:"open"`
	High     float64   `json:"high"`
	Low      float64   `json:"low"`
	Close    float64   `json:"close"`
	AdjClose *float64  `json:"adj_close"`
	Volume   int64     `json:"volume"`
}

func (q *Queries) ListCandlesDesc(ctx context.Context, arg ListCandlesDescParams) ([]ListCandlesDescRow, error) {
	rows, err := q.db.Query(ctx, listCandlesDesc,
		arg.SymbolID,
		arg.Timeframe,
		arg.Ts,
		arg.Ts_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCandlesDescRow{}
	for rows.Next() {
		var i ListCandlesDescRow
		if err := rows.Scan(
			&i.Ts,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.AdjClose,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
