// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chart_layouts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countChartLayouts = `-- name: CountChartLayouts :one
SELECT COUNT(*) FROM chart_layouts
WHERE user_id = $1
`

func (q *Queries) CountChartLayouts(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChartLayouts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChartLayout = `-- name: CreateChartLayout :one
INSERT INTO chart_layouts (user_id, name, layout)
VALUES ($1, $2, $3)
RETURNING user_id, layout, created_at, updated_at, id, name
`

type CreateChartLayoutParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Layout []byte    `json:"layout"`
}

func (q *Queries) CreateChartLayout(ctx context.Context, arg CreateChartLayoutParams) (ChartLayout, error) {
	row := q.db.QueryRow(ctx, createChartLayout, arg.UserID, arg.Name, arg.Layout)
	var i ChartLayout
	err := row.Scan(
		&i.UserID,
		&i.Layout,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
		&i.Name,
	)
	return i, err
}

const deleteChartLayout = `-- name: DeleteChartLayout :execrows
DELETE FROM chart_layouts
WHERE id = $1 AND user_id = $2
`

type DeleteChartLayoutParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteChartLayout(ctx context.Context, arg DeleteChartLayoutParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChartLayout, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listChartLayouts = `-- name: ListChartLayouts :many
SELECT user_id, layout, created_at, updated_at, id, name FROM chart_layouts
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListChartLayouts(ctx context.Context, userID uuid.UUID) ([]ChartLayout, error) {
	rows, err := q.db.Query(ctx, listChartLayouts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChartLayout{}
	for rows.Next() {
		var i ChartLayout
		if err := rows.Scan(
			&i.UserID,
			&i.Layout,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChartLayout = `-- name: UpdateChartLayout :one
UPDATE chart_layouts
SET name = $3, layout = $4, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING user_id, layout, created_at, updated_at, id, name
`

type UpdateChartLayoutParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Layout []byte    `json:"layout"`
}

func (q *Queries) UpdateChartLayout(ctx context.Context, arg UpdateChartLayoutParams) (ChartLayout, error) {
	row := q.db.QueryRow(ctx, updateChartLayout,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Layout,
	)
	var i ChartLayout
	err := row.Scan(
		&i.UserID,
		&i.Layout,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
		&i.Name,
	)
	return i, err
}
