// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForCreateBacktestEquity implements pgx.CopyFromSource.
type iteratorForCreateBacktestEquity struct {
	rows                 []CreateBacktestEquityParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBacktestEquity) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBacktestEquity) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RunID,
		r.rows[0].Ts,
		r.rows[0].EquityCents,
		r.rows[0].HoldCents,
		r.rows[0].IndexCents,
	}, nil
}

func (r iteratorForCreateBacktestEquity) Err() error {
	return nil
}

func (q *Queries) CreateBacktestEquity(ctx context.Context, arg []CreateBacktestEquityParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"backtest_equity"}, []string{"run_id", "ts", "equity_cents", "hold_cents", "index_cents"}, &iteratorForCreateBacktestEquity{rows: arg})
}

// iteratorForCreateBacktestTrades implements pgx.CopyFromSource.
type iteratorForCreateBacktestTrades struct {
	rows                 []CreateBacktestTradesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBacktestTrades) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBacktestTrades) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RunID,
		r.rows[0].Seq,
		r.rows[0].Side,
		r.rows[0].Qty,
		r.rows[0].EntryTs,
		r.rows[0].EntryPrice,
		r.rows[0].ExitTs,
		r.rows[0].ExitPrice,
		r.rows[0].PnlCents,
		r.rows[0].FeesCents,
		r.rows[0].DividendsCents,
		r.rows[0].ExitReason,
	}, nil
}

func (r iteratorForCreateBacktestTrades) Err() error {
	return nil
}

func (q *Queries) CreateBacktestTrades(ctx context.Context, arg []CreateBacktestTradesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"backtest_trades"}, []string{"run_id", "seq", "side", "qty", "entry_ts", "entry_price", "exit_ts", "exit_price", "pnl_cents", "fees_cents", "dividends_cents", "exit_reason"}, &iteratorForCreateBacktestTrades{rows: arg})
}
