// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: futures.sql

package database

import (
	"context"
	"time"
)

const countFuturesQuotes = `-- name: CountFuturesQuotes :one
SELECT count(*) FROM futures_quotes
WHERE contract_id = $1
`

func (q *Queries) CountFuturesQuotes(ctx context.Context, contractID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFuturesQuotes, contractID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFuturesContract = `-- name: GetFuturesContract :one
SELECT id, symbol, root, description, segment, multiplier, lot_size, currency, isin, first_trade, last_trade, expiration, seen_at FROM futures_contracts
WHERE symbol = $1
`

func (q *Queries) GetFuturesContract(ctx context.Context, symbol string) (FuturesContract, error) {
	row := q.db.QueryRow(ctx, getFuturesContract, symbol)
	var i FuturesContract
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Root,
		&i.Description,
		&i.Segment,
		&i.Multiplier,
		&i.LotSize,
		&i.Currency,
		&i.Isin,
		&i.FirstTrade,
		&i.LastTrade,
		&i.Expiration,
		&i.SeenAt,
	)
	return i, err
}

const latestFuturesQuoteDay = `-- name: LatestFuturesQuoteDay :one
SELECT day FROM futures_quotes q
JOIN futures_contracts c ON c.id = q.contract_id
WHERE c.root = $1
ORDER BY q.day DESC
LIMIT 1
`

func (q *Queries) LatestFuturesQuoteDay(ctx context.Context, root string) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestFuturesQuoteDay, root)
	var day time.Time
	err := row.Scan(&day)
	return day, err
}

const listFuturesContractsByRoot = `-- name: ListFuturesContractsByRoot :many
SELECT id, symbol, root, description, segment, multiplier, lot_size, currency, isin, first_trade, last_trade, expiration, seen_at FROM futures_contracts
WHERE root = $1
ORDER BY expiration
`

func (q *Queries) ListFuturesContractsByRoot(ctx context.Context, root string) ([]FuturesContract, error) {
	rows, err := q.db.Query(ctx, listFuturesContractsByRoot, root)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuturesContract{}
	for rows.Next() {
		var i FuturesContract
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Root,
			&i.Description,
			&i.Segment,
			&i.Multiplier,
			&i.LotSize,
			&i.Currency,
			&i.Isin,
			&i.FirstTrade,
			&i.LastTrade,
			&i.Expiration,
			&i.SeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFuturesQuotesByRoot = `-- name: ListFuturesQuotesByRoot :many
SELECT c.symbol, c.expiration, c.multiplier, q.day, q.settlement, q.high, q.low, q.close, q.average, q.volume, q.trades
FROM futures_quotes q
JOIN futures_contracts c ON c.id = q.contract_id
WHERE c.root = $1 AND q.day >= $2 AND q.day <= $3
ORDER BY q.day, c.expiration
`

type ListFuturesQuotesByRootParams struct {
	Root  string    `json:"root"`
	Day   time.Time `json:"day"`
	Day_2 time.Time `json:"day_2"`
}

type ListFuturesQuotesByRootRow struct {
	Symbol     string    `json:"symbol"`
	Expiration time.Time `json:"expiration"`
	Multiplier float64   `json:"multiplier"`
	Day        time.Time `json:"day"`
	Settlement float64   `json:"settlement"`
	High       *float64  `json:"high"`
	Low        *float64  `json:"low"`
	Close      *float64  `json:"close"`
	Average    *float64  `json:"average"`
	Volume     *int64    `json:"volume"`
	Trades     *int64    `json:"trades"`
}

func (q *Queries) ListFuturesQuotesByRoot(ctx context.Context, arg ListFuturesQuotesByRootParams) ([]ListFuturesQuotesByRootRow, error) {
	rows, err := q.db.Query(ctx, listFuturesQuotesByRoot, arg.Root, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFuturesQuotesByRootRow{}
	for rows.Next() {
		var i ListFuturesQuotesByRootRow
		if err := rows.Scan(
			&i.Symbol,
			&i.Expiration,
			&i.Multiplier,
			&i.Day,
			&i.Settlement,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Average,
			&i.Volume,
			&i.Trades,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFuturesRoots = `-- name: ListFuturesRoots :many
SELECT DISTINCT root FROM futures_contracts
ORDER BY root
`

func (q *Queries) ListFuturesRoots(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listFuturesRoots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var root string
		if err := rows.Scan(&root); err != nil {
			return nil, err
		}
		items = append(items, root)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFuturesContract = `-- name: UpsertFuturesContract :one
INSERT INTO futures_contracts (
    symbol, root, description, segment, multiplier, lot_size, currency, isin, first_trade, last_trade, expiration
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (symbol) DO UPDATE SET
    root        = EXCLUDED.root,
    description = EXCLUDED.description,
    segment     = EXCLUDED.segment,
    multiplier  = EXCLUDED.multiplier,
    lot_size    = EXCLUDED.lot_size,
    currency    = EXCLUDED.currency,
    isin        = EXCLUDED.isin,
    first_trade = EXCLUDED.first_trade,
    last_trade  = EXCLUDED.last_trade,
    expiration  = EXCLUDED.expiration,
    seen_at     = NOW()
RETURNING id, symbol, root, description, segment, multiplier, lot_size, currency, isin, first_trade, last_trade, expiration, seen_at
`

type UpsertFuturesContractParams struct {
	Symbol      string     `json:"symbol"`
	Root        string     `json:"root"`
	Description *string    `json:"description"`
	Segment     *string    `json:"segment"`
	Multiplier  float64    `json:"multiplier"`
	LotSize     int32      `json:"lot_size"`
	Currency    string     `json:"currency"`
	Isin        *string    `json:"isin"`
	FirstTrade  *time.Time `json:"first_trade"`
	LastTrade   *time.Time `json:"last_trade"`
	Expiration  time.Time  `json:"expiration"`
}

func (q *Queries) UpsertFuturesContract(ctx context.Context, arg UpsertFuturesContractParams) (FuturesContract, error) {
	row := q.db.QueryRow(ctx, upsertFuturesContract,
		arg.Symbol,
		arg.Root,
		arg.Description,
		arg.Segment,
		arg.Multiplier,
		arg.LotSize,
		arg.Currency,
		arg.Isin,
		arg.FirstTrade,
		arg.LastTrade,
		arg.Expiration,
	)
	var i FuturesContract
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Root,
		&i.Description,
		&i.Segment,
		&i.Multiplier,
		&i.LotSize,
		&i.Currency,
		&i.Isin,
		&i.FirstTrade,
		&i.LastTrade,
		&i.Expiration,
		&i.SeenAt,
	)
	return i, err
}
