// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest_runs.sql

package database

import (
	"context"
	"time"
)

const countCompletedIngestRuns = `-- name: CountCompletedIngestRuns :one
SELECT count(*)
FROM ingest_runs
WHERE symbol_id = $1
  AND timeframe = $2
  AND status IN ('ok', 'empty')
  AND range_start <= $3
  AND range_end >= $4
`

type CountCompletedIngestRunsParams struct {
	SymbolID   int64     `json:"symbol_id"`
	Timeframe  string    `json:"timeframe"`
	RangeStart time.Time `json:"range_start"`
	RangeEnd   time.Time `json:"range_end"`
}

func (q *Queries) CountCompletedIngestRuns(ctx context.Context, arg CountCompletedIngestRunsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedIngestRuns,
		arg.SymbolID,
		arg.Timeframe,
		arg.RangeStart,
		arg.RangeEnd,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishIngestRun = `-- name: FinishIngestRun :exec
UPDATE ingest_runs
SET status      = $2,
    http_status = $3,
    bars        = $4,
    rejected    = $5,
    error       = $6,
    finished_at = NOW(),
    duration_ms = $7
WHERE id = $1
`

type FinishIngestRunParams struct {
	ID         int64   `json:"id"`
	Status     string  `json:"status"`
	HttpStatus *int32  `json:"http_status"`
	Bars       int32   `json:"bars"`
	Rejected   int32   `json:"rejected"`
	Error      *string `json:"error"`
	DurationMs *int32  `json:"duration_ms"`
}

func (q *Queries) FinishIngestRun(ctx context.Context, arg FinishIngestRunParams) error {
	_, err := q.db.Exec(ctx, finishIngestRun,
		arg.ID,
		arg.Status,
		arg.HttpStatus,
		arg.Bars,
		arg.Rejected,
		arg.Error,
		arg.DurationMs,
	)
	return err
}

const listIngestRuns = `-- name: ListIngestRuns :many
SELECT id, symbol_id, timeframe, range_start, range_end, status, http_status, bars, rejected, error, started_at, finished_at, duration_ms FROM ingest_runs
WHERE symbol_id = $1 AND timeframe = $2
ORDER BY started_at DESC
LIMIT $3
`

type ListIngestRunsParams struct {
	SymbolID  int64  `json:"symbol_id"`
	Timeframe string `json:"timeframe"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListIngestRuns(ctx context.Context, arg ListIngestRunsParams) ([]IngestRun, error) {
	rows, err := q.db.Query(ctx, listIngestRuns, arg.SymbolID, arg.Timeframe, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestRun{}
	for rows.Next() {
		var i IngestRun
		if err := rows.Scan(
			&i.ID,
			&i.SymbolID,
			&i.Timeframe,
			&i.RangeStart,
			&i.RangeEnd,
			&i.Status,
			&i.HttpStatus,
			&i.Bars,
			&i.Rejected,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentIngestFailures = `-- name: ListRecentIngestFailures :many
SELECT id, symbol_id, timeframe, range_start, range_end, status, http_status, bars, rejected, error, started_at, finished_at, duration_ms FROM ingest_runs
WHERE status = 'failed' AND started_at >= $1
ORDER BY started_at DESC
LIMIT $2
`

type ListRecentIngestFailuresParams struct {
	StartedAt time.Time `json:"started_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListRecentIngestFailures(ctx context.Context, arg ListRecentIngestFailuresParams) ([]IngestRun, error) {
	rows, err := q.db.Query(ctx, listRecentIngestFailures, arg.StartedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestRun{}
	for rows.Next() {
		var i IngestRun
		if err := rows.Scan(
			&i.ID,
			&i.SymbolID,
			&i.Timeframe,
			&i.RangeStart,
			&i.RangeEnd,
			&i.Status,
			&i.HttpStatus,
			&i.Bars,
			&i.Rejected,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startIngestRun = `-- name: StartIngestRun :one
INSERT INTO ingest_runs (symbol_id, timeframe, range_start, range_end, status)
VALUES ($1, $2, $3, $4, 'running')
RETURNING id
`

type StartIngestRunParams struct {
	SymbolID   int64     `json:"symbol_id"`
	Timeframe  string    `json:"timeframe"`
	RangeStart time.Time `json:"range_start"`
	RangeEnd   time.Time `json:"range_end"`
}

func (q *Queries) StartIngestRun(ctx context.Context, arg StartIngestRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, startIngestRun,
		arg.SymbolID,
		arg.Timeframe,
		arg.RangeStart,
		arg.RangeEnd,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
