// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type BrapiUsage struct {
	Day      time.Time `json:"day"`
	Requests int32     `json:"requests"`
}

type Candle struct {
	SymbolID  int64     `json:"symbol_id"`
	Timeframe string    `json:"timeframe"`
	Ts        time.Time `json:"ts"`
	Open      float64   `json:"open"`
	High      float64   `json:"high"`
	Low       float64   `json:"low"`
	Close     float64   `json:"close"`
	AdjClose  *float64  `json:"adj_close"`
	Volume    int64     `json:"volume"`
}

type IngestRun struct {
	ID         int64      `json:"id"`
	SymbolID   int64      `json:"symbol_id"`
	Timeframe  string     `json:"timeframe"`
	RangeStart time.Time  `json:"range_start"`
	RangeEnd   time.Time  `json:"range_end"`
	Status     string     `json:"status"`
	HttpStatus *int32     `json:"http_status"`
	Bars       int32      `json:"bars"`
	Rejected   int32      `json:"rejected"`
	Error      *string    `json:"error"`
	StartedAt  time.Time  `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at"`
	DurationMs *int32     `json:"duration_ms"`
}

type RefreshToken struct {
	TokenHash string     `json:"token_hash"`
	UserID    uuid.UUID  `json:"user_id"`
	ExpiresAt time.Time  `json:"expires_at"`
	RevokedAt *time.Time `json:"revoked_at"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type Symbol struct {
	ID         int64      `json:"id"`
	Ticker     string     `json:"ticker"`
	ShortName  *string    `json:"short_name"`
	LongName   *string    `json:"long_name"`
	Kind       string     `json:"kind"`
	Currency   string     `json:"currency"`
	LotSize    int32      `json:"lot_size"`
	TickSize   float64    `json:"tick_size"`
	PointValue *float64   `json:"point_value"`
	Active     bool       `json:"active"`
	Tracked    bool       `json:"tracked"`
	FirstSeen  *time.Time `json:"first_seen"`
	LastSeen   *time.Time `json:"last_seen"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
