// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type BrapiUsage struct {
	Day      time.Time `json:"day"`
	Requests int32     `json:"requests"`
}

type Symbol struct {
	ID         int64      `json:"id"`
	Ticker     string     `json:"ticker"`
	ShortName  *string    `json:"short_name"`
	LongName   *string    `json:"long_name"`
	Kind       string     `json:"kind"`
	Currency   string     `json:"currency"`
	LotSize    int32      `json:"lot_size"`
	TickSize   float64    `json:"tick_size"`
	PointValue *float64   `json:"point_value"`
	Active     bool       `json:"active"`
	Tracked    bool       `json:"tracked"`
	FirstSeen  *time.Time `json:"first_seen"`
	LastSeen   *time.Time `json:"last_seen"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}
