// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type BacktestEquity struct {
	RunID       uuid.UUID `json:"run_id"`
	Ts          time.Time `json:"ts"`
	EquityCents int64     `json:"equity_cents"`
	HoldCents   *int64    `json:"hold_cents"`
	IndexCents  *int64    `json:"index_cents"`
}

type BacktestRun struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	StrategyID   uuid.UUID  `json:"strategy_id"`
	Spec         []byte     `json:"spec"`
	SymbolID     int64      `json:"symbol_id"`
	Timeframe    string     `json:"timeframe"`
	StartDate    time.Time  `json:"start_date"`
	EndDate      time.Time  `json:"end_date"`
	CapitalCents int64      `json:"capital_cents"`
	Status       string     `json:"status"`
	Metrics      []byte     `json:"metrics"`
	Error        *string    `json:"error"`
	CreatedAt    time.Time  `json:"created_at"`
	StartedAt    *time.Time `json:"started_at"`
	FinishedAt   *time.Time `json:"finished_at"`
	MaxPositions int32      `json:"max_positions"`
	SweepID      *uuid.UUID `json:"sweep_id"`
	Params       []byte     `json:"params"`
	Point        *int32     `json:"point"`
	Fold         *int32     `json:"fold"`
	Phase        *string    `json:"phase"`
}

type BacktestRunSymbol struct {
	RunID    uuid.UUID `json:"run_id"`
	Ord      int32     `json:"ord"`
	SymbolID int64     `json:"symbol_id"`
}

type BacktestSweep struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	StrategyID   uuid.UUID `json:"strategy_id"`
	Kind         string    `json:"kind"`
	Spec         []byte    `json:"spec"`
	Axes         []byte    `json:"axes"`
	Folds        []byte    `json:"folds"`
	Objective    string    `json:"objective"`
	SymbolID     int64     `json:"symbol_id"`
	Timeframe    string    `json:"timeframe"`
	StartDate    time.Time `json:"start_date"`
	EndDate      time.Time `json:"end_date"`
	CapitalCents int64     `json:"capital_cents"`
	MaxPositions int32     `json:"max_positions"`
	Points       int32     `json:"points"`
	CreatedAt    time.Time `json:"created_at"`
}

type BacktestSweepSymbol struct {
	SweepID  uuid.UUID `json:"sweep_id"`
	Ord      int32     `json:"ord"`
	SymbolID int64     `json:"symbol_id"`
}

type BacktestSymbolEquity struct {
	RunID       uuid.UUID `json:"run_id"`
	SymbolID    int64     `json:"symbol_id"`
	Ts          time.Time `json:"ts"`
	EquityCents int64     `json:"equity_cents"`
}

type BacktestTrade struct {
	RunID          uuid.UUID  `json:"run_id"`
	Seq            int32      `json:"seq"`
	Side           string     `json:"side"`
	Qty            int64      `json:"qty"`
	EntryTs        time.Time  `json:"entry_ts"`
	EntryPrice     float64    `json:"entry_price"`
	ExitTs         *time.Time `json:"exit_ts"`
	ExitPrice      *float64   `json:"exit_price"`
	PnlCents       *int64     `json:"pnl_cents"`
	FeesCents      int64      `json:"fees_cents"`
	ExitReason     *string    `json:"exit_reason"`
	DividendsCents int64      `json:"dividends_cents"`
	BorrowCents    int64      `json:"borrow_cents"`
	SplitCashCents int64      `json:"split_cash_cents"`
	SymbolID       int64      `json:"symbol_id"`
}

type BrapiUsage struct {
	Day      time.Time `json:"day"`
	Requests int32     `json:"requests"`
}

type Candle struct {
	SymbolID  int64     `json:"symbol_id"`
	Timeframe string    `json:"timeframe"`
	Ts        time.Time `json:"ts"`
	Open      float64   `json:"open"`
	High      float64   `json:"high"`
	Low       float64   `json:"low"`
	Close     float64   `json:"close"`
	AdjClose  *float64  `json:"adj_close"`
	Volume    int64     `json:"volume"`
}

type ChartLayout struct {
	UserID    uuid.UUID `json:"user_id"`
	Layout    []byte    `json:"layout"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
}

type FuturesContract struct {
	ID          int64      `json:"id"`
	Symbol      string     `json:"symbol"`
	Root        string     `json:"root"`
	Description *string    `json:"description"`
	Segment     *string    `json:"segment"`
	Multiplier  float64    `json:"multiplier"`
	LotSize     int32      `json:"lot_size"`
	Currency    string     `json:"currency"`
	Isin        *string    `json:"isin"`
	FirstTrade  *time.Time `json:"first_trade"`
	LastTrade   *time.Time `json:"last_trade"`
	Expiration  time.Time  `json:"expiration"`
	SeenAt      time.Time  `json:"seen_at"`
}

type FuturesQuote struct {
	ContractID int64     `json:"contract_id"`
	Day        time.Time `json:"day"`
	Settlement float64   `json:"settlement"`
	High       *float64  `json:"high"`
	Low        *float64  `json:"low"`
	Close      *float64  `json:"close"`
	Average    *float64  `json:"average"`
	Volume     *int64    `json:"volume"`
	Trades     *int64    `json:"trades"`
}

type IngestRun struct {
	ID         int64      `json:"id"`
	SymbolID   int64      `json:"symbol_id"`
	Timeframe  string     `json:"timeframe"`
	RangeStart time.Time  `json:"range_start"`
	RangeEnd   time.Time  `json:"range_end"`
	Status     string     `json:"status"`
	HttpStatus *int32     `json:"http_status"`
	Bars       int32      `json:"bars"`
	Rejected   int32      `json:"rejected"`
	Error      *string    `json:"error"`
	StartedAt  time.Time  `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at"`
	DurationMs *int32     `json:"duration_ms"`
}

type RefreshToken struct {
	TokenHash string     `json:"token_hash"`
	UserID    uuid.UUID  `json:"user_id"`
	ExpiresAt time.Time  `json:"expires_at"`
	RevokedAt *time.Time `json:"revoked_at"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type Strategy struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Spec        []byte     `json:"spec"`
	Version     int32      `json:"version"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ShareToken  *string    `json:"share_token"`
	SharedAt    *time.Time `json:"shared_at"`
}

type Symbol struct {
	ID         int64      `json:"id"`
	Ticker     string     `json:"ticker"`
	ShortName  *string    `json:"short_name"`
	LongName   *string    `json:"long_name"`
	Kind       string     `json:"kind"`
	Currency   string     `json:"currency"`
	LotSize    int32      `json:"lot_size"`
	TickSize   float64    `json:"tick_size"`
	PointValue *float64   `json:"point_value"`
	Active     bool       `json:"active"`
	Tracked    bool       `json:"tracked"`
	FirstSeen  *time.Time `json:"first_seen"`
	LastSeen   *time.Time `json:"last_seen"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type SymbolBasket struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SymbolBasketSymbol struct {
	BasketID uuid.UUID `json:"basket_id"`
	Ord      int32     `json:"ord"`
	SymbolID int64     `json:"symbol_id"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
