// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sweeps.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveSweeps = `-- name: CountActiveSweeps :one
SELECT COUNT(DISTINCT w.id) FROM backtest_sweeps w
JOIN backtest_runs r ON r.sweep_id = w.id
WHERE w.user_id = $1 AND r.status IN ('queued', 'running')
`

func (q *Queries) CountActiveSweeps(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSweeps, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSweep = `-- name: CreateSweep :one
INSERT INTO backtest_sweeps (
    user_id, strategy_id, kind, spec, axes, folds, objective,
    symbol_id, timeframe, start_date, end_date, capital_cents,
    max_positions, points
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14
)
RETURNING id, user_id, strategy_id, kind, spec, axes, folds, objective, symbol_id, timeframe, start_date, end_date, capital_cents, max_positions, points, created_at
`

type CreateSweepParams struct {
	UserID       uuid.UUID `json:"user_id"`
	StrategyID   uuid.UUID `json:"strategy_id"`
	Kind         string    `json:"kind"`
	Spec         []byte    `json:"spec"`
	Axes         []byte    `json:"axes"`
	Folds        []byte    `json:"folds"`
	Objective    string    `json:"objective"`
	SymbolID     int64     `json:"symbol_id"`
	Timeframe    string    `json:"timeframe"`
	StartDate    time.Time `json:"start_date"`
	EndDate      time.Time `json:"end_date"`
	CapitalCents int64     `json:"capital_cents"`
	MaxPositions int32     `json:"max_positions"`
	Points       int32     `json:"points"`
}

func (q *Queries) CreateSweep(ctx context.Context, arg CreateSweepParams) (BacktestSweep, error) {
	row := q.db.QueryRow(ctx, createSweep,
		arg.UserID,
		arg.StrategyID,
		arg.Kind,
		arg.Spec,
		arg.Axes,
		arg.Folds,
		arg.Objective,
		arg.SymbolID,
		arg.Timeframe,
		arg.StartDate,
		arg.EndDate,
		arg.CapitalCents,
		arg.MaxPositions,
		arg.Points,
	)
	var i BacktestSweep
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StrategyID,
		&i.Kind,
		&i.Spec,
		&i.Axes,
		&i.Folds,
		&i.Objective,
		&i.SymbolID,
		&i.Timeframe,
		&i.StartDate,
		&i.EndDate,
		&i.CapitalCents,
		&i.MaxPositions,
		&i.Points,
		&i.CreatedAt,
	)
	return i, err
}

type CreateSweepRunsParams struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	StrategyID   uuid.UUID  `json:"strategy_id"`
	Spec         []byte     `json:"spec"`
	SymbolID     int64      `json:"symbol_id"`
	Timeframe    string     `json:"timeframe"`
	StartDate    time.Time  `json:"start_date"`
	EndDate      time.Time  `json:"end_date"`
	CapitalCents int64      `json:"capital_cents"`
	MaxPositions int32      `json:"max_positions"`
	Status       string     `json:"status"`
	SweepID      *uuid.UUID `json:"sweep_id"`
	Params       []byte     `json:"params"`
	Point        *int32     `json:"point"`
	Fold         *int32     `json:"fold"`
	Phase        *string    `json:"phase"`
}

type CreateSweepSymbolsParams struct {
	SweepID  uuid.UUID `json:"sweep_id"`
	Ord      int32     `json:"ord"`
	SymbolID int64     `json:"symbol_id"`
}

const deleteSweep = `-- name: DeleteSweep :execrows
DELETE FROM backtest_sweeps
WHERE id = $1 AND user_id = $2
`

type DeleteSweepParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSweep(ctx context.Context, arg DeleteSweepParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSweep, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSweep = `-- name: GetSweep :one
SELECT w.id, w.user_id, w.strategy_id, w.kind, w.spec, w.axes, w.folds, w.objective, w.symbol_id, w.timeframe, w.start_date, w.end_date, w.capital_cents, w.max_positions, w.points, w.created_at, s.ticker
FROM backtest_sweeps w
JOIN symbols s ON s.id = w.symbol_id
WHERE w.id = $1 AND w.user_id = $2
`

type GetSweepParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetSweepRow struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	StrategyID   uuid.UUID `json:"strategy_id"`
	Kind         string    `json:"kind"`
	Spec         []byte    `json:"spec"`
	Axes         []byte    `json:"axes"`
	Folds        []byte    `json:"folds"`
	Objective    string    `json:"objective"`
	SymbolID     int64     `json:"symbol_id"`
	Timeframe    string    `json:"timeframe"`
	StartDate    time.Time `json:"start_date"`
	EndDate      time.Time `json:"end_date"`
	CapitalCents int64     `json:"capital_cents"`
	MaxPositions int32     `json:"max_positions"`
	Points       int32     `json:"points"`
	CreatedAt    time.Time `json:"created_at"`
	Ticker       string    `json:"ticker"`
}

func (q *Queries) GetSweep(ctx context.Context, arg GetSweepParams) (GetSweepRow, error) {
	row := q.db.QueryRow(ctx, getSweep, arg.ID, arg.UserID)
	var i GetSweepRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StrategyID,
		&i.Kind,
		&i.Spec,
		&i.Axes,
		&i.Folds,
		&i.Objective,
		&i.SymbolID,
		&i.Timeframe,
		&i.StartDate,
		&i.EndDate,
		&i.CapitalCents,
		&i.MaxPositions,
		&i.Points,
		&i.CreatedAt,
		&i.Ticker,
	)
	return i, err
}

const getSweepByID = `-- name: GetSweepByID :one
SELECT id, user_id, strategy_id, kind, spec, axes, folds, objective, symbol_id, timeframe, start_date, end_date, capital_cents, max_positions, points, created_at FROM backtest_sweeps WHERE id = $1
`

func (q *Queries) GetSweepByID(ctx context.Context, id uuid.UUID) (BacktestSweep, error) {
	row := q.db.QueryRow(ctx, getSweepByID, id)
	var i BacktestSweep
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StrategyID,
		&i.Kind,
		&i.Spec,
		&i.Axes,
		&i.Folds,
		&i.Objective,
		&i.SymbolID,
		&i.Timeframe,
		&i.StartDate,
		&i.EndDate,
		&i.CapitalCents,
		&i.MaxPositions,
		&i.Points,
		&i.CreatedAt,
	)
	return i, err
}

const listSweepFoldRuns = `-- name: ListSweepFoldRuns :many
SELECT id, params, point, spec, metrics
FROM backtest_runs
WHERE sweep_id = $1 AND fold = $2 AND phase = 'in_sample' AND status = 'done'
ORDER BY point
`

type ListSweepFoldRunsParams struct {
	SweepID *uuid.UUID `json:"sweep_id"`
	Fold    *int32     `json:"fold"`
}

type ListSweepFoldRunsRow struct {
	ID      uuid.UUID `json:"id"`
	Params  []byte    `json:"params"`
	Point   *int32    `json:"point"`
	Spec    []byte    `json:"spec"`
	Metrics []byte    `json:"metrics"`
}

func (q *Queries) ListSweepFoldRuns(ctx context.Context, arg ListSweepFoldRunsParams) ([]ListSweepFoldRunsRow, error) {
	rows, err := q.db.Query(ctx, listSweepFoldRuns, arg.SweepID, arg.Fold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSweepFoldRunsRow{}
	for rows.Next() {
		var i ListSweepFoldRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Params,
			&i.Point,
			&i.Spec,
			&i.Metrics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweepRuns = `-- name: ListSweepRuns :many
SELECT id, params, point, fold, phase, status, metrics, error,
       start_date, end_date, created_at, finished_at
FROM backtest_runs
WHERE sweep_id = $1
ORDER BY fold, phase, point
`

type ListSweepRunsRow struct {
	ID         uuid.UUID  `json:"id"`
	Params     []byte     `json:"params"`
	Point      *int32     `json:"point"`
	Fold       *int32     `json:"fold"`
	Phase      *string    `json:"phase"`
	Status     string     `json:"status"`
	Metrics    []byte     `json:"metrics"`
	Error      *string    `json:"error"`
	StartDate  time.Time  `json:"start_date"`
	EndDate    time.Time  `json:"end_date"`
	CreatedAt  time.Time  `json:"created_at"`
	FinishedAt *time.Time `json:"finished_at"`
}

func (q *Queries) ListSweepRuns(ctx context.Context, sweepID *uuid.UUID) ([]ListSweepRunsRow, error) {
	rows, err := q.db.Query(ctx, listSweepRuns, sweepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSweepRunsRow{}
	for rows.Next() {
		var i ListSweepRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Params,
			&i.Point,
			&i.Fold,
			&i.Phase,
			&i.Status,
			&i.Metrics,
			&i.Error,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweepSymbols = `-- name: ListSweepSymbols :many
SELECT ws.ord, s.id, s.ticker
FROM backtest_sweep_symbols ws
JOIN symbols s ON s.id = ws.symbol_id
WHERE ws.sweep_id = $1
ORDER BY ws.ord
`

type ListSweepSymbolsRow struct {
	Ord    int32  `json:"ord"`
	ID     int64  `json:"id"`
	Ticker string `json:"ticker"`
}

func (q *Queries) ListSweepSymbols(ctx context.Context, sweepID uuid.UUID) ([]ListSweepSymbolsRow, error) {
	rows, err := q.db.Query(ctx, listSweepSymbols, sweepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSweepSymbolsRow{}
	for rows.Next() {
		var i ListSweepSymbolsRow
		if err := rows.Scan(&i.Ord, &i.ID, &i.Ticker); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweeps = `-- name: ListSweeps :many
SELECT w.id, w.user_id, w.strategy_id, w.kind, w.spec, w.axes, w.folds, w.objective, w.symbol_id, w.timeframe, w.start_date, w.end_date, w.capital_cents, w.max_positions, w.points, w.created_at, s.ticker
FROM backtest_sweeps w
JOIN symbols s ON s.id = w.symbol_id
WHERE w.user_id = $1
ORDER BY w.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSweepsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListSweepsRow struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	StrategyID   uuid.UUID `json:"strategy_id"`
	Kind         string    `json:"kind"`
	Spec         []byte    `json:"spec"`
	Axes         []byte    `json:"axes"`
	Folds        []byte    `json:"folds"`
	Objective    string    `json:"objective"`
	SymbolID     int64     `json:"symbol_id"`
	Timeframe    string    `json:"timeframe"`
	StartDate    time.Time `json:"start_date"`
	EndDate      time.Time `json:"end_date"`
	CapitalCents int64     `json:"capital_cents"`
	MaxPositions int32     `json:"max_positions"`
	Points       int32     `json:"points"`
	CreatedAt    time.Time `json:"created_at"`
	Ticker       string    `json:"ticker"`
}

func (q *Queries) ListSweeps(ctx context.Context, arg ListSweepsParams) ([]ListSweepsRow, error) {
	rows, err := q.db.Query(ctx, listSweeps, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSweepsRow{}
	for rows.Next() {
		var i ListSweepsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StrategyID,
			&i.Kind,
			&i.Spec,
			&i.Axes,
			&i.Folds,
			&i.Objective,
			&i.SymbolID,
			&i.Timeframe,
			&i.StartDate,
			&i.EndDate,
			&i.CapitalCents,
			&i.MaxPositions,
			&i.Points,
			&i.CreatedAt,
			&i.Ticker,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readyWalkForwardFolds = `-- name: ReadyWalkForwardFolds :many
SELECT r.sweep_id, r.fold
FROM backtest_runs r
JOIN backtest_sweeps w ON w.id = r.sweep_id
WHERE w.kind = 'walk_forward' AND r.phase = 'in_sample'
GROUP BY r.sweep_id, r.fold
HAVING COUNT(*) FILTER (WHERE r.status IN ('queued', 'running')) = 0
   AND COUNT(*) FILTER (WHERE r.status = 'done') > 0
   AND NOT EXISTS (
       SELECT 1 FROM backtest_runs o
       WHERE o.sweep_id = r.sweep_id AND o.fold = r.fold AND o.phase = 'out_of_sample'
   )
`

type ReadyWalkForwardFoldsRow struct {
	SweepID *uuid.UUID `json:"sweep_id"`
	Fold    *int32     `json:"fold"`
}

func (q *Queries) ReadyWalkForwardFolds(ctx context.Context) ([]ReadyWalkForwardFoldsRow, error) {
	rows, err := q.db.Query(ctx, readyWalkForwardFolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadyWalkForwardFoldsRow{}
	for rows.Next() {
		var i ReadyWalkForwardFoldsRow
		if err := rows.Scan(&i.SweepID, &i.Fold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sweepProgress = `-- name: SweepProgress :one
SELECT COUNT(*) AS total,
       COUNT(*) FILTER (WHERE status = 'queued') AS queued,
       COUNT(*) FILTER (WHERE status = 'running') AS running,
       COUNT(*) FILTER (WHERE status = 'done') AS done,
       COUNT(*) FILTER (WHERE status = 'error') AS failed
FROM backtest_runs
WHERE sweep_id = $1
`

type SweepProgressRow struct {
	Total   int64 `json:"total"`
	Queued  int64 `json:"queued"`
	Running int64 `json:"running"`
	Done    int64 `json:"done"`
	Failed  int64 `json:"failed"`
}

func (q *Queries) SweepProgress(ctx context.Context, sweepID *uuid.UUID) (SweepProgressRow, error) {
	row := q.db.QueryRow(ctx, sweepProgress, sweepID)
	var i SweepProgressRow
	err := row.Scan(
		&i.Total,
		&i.Queued,
		&i.Running,
		&i.Done,
		&i.Failed,
	)
	return i, err
}
