// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: symbol_baskets.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSymbolBaskets = `-- name: CountSymbolBaskets :one
SELECT COUNT(*) FROM symbol_baskets
WHERE user_id = $1
`

func (q *Queries) CountSymbolBaskets(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSymbolBaskets, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSymbolBasket = `-- name: CreateSymbolBasket :one
INSERT INTO symbol_baskets (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateSymbolBasketParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateSymbolBasket(ctx context.Context, arg CreateSymbolBasketParams) (SymbolBasket, error) {
	row := q.db.QueryRow(ctx, createSymbolBasket, arg.UserID, arg.Name)
	var i SymbolBasket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateSymbolBasketSymbolsParams struct {
	BasketID uuid.UUID `json:"basket_id"`
	Ord      int32     `json:"ord"`
	SymbolID int64     `json:"symbol_id"`
}

const deleteSymbolBasket = `-- name: DeleteSymbolBasket :execrows
DELETE FROM symbol_baskets
WHERE id = $1 AND user_id = $2
`

type DeleteSymbolBasketParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSymbolBasket(ctx context.Context, arg DeleteSymbolBasketParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSymbolBasket, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSymbolBasketSymbols = `-- name: DeleteSymbolBasketSymbols :exec
DELETE FROM symbol_basket_symbols
WHERE basket_id = $1
`

func (q *Queries) DeleteSymbolBasketSymbols(ctx context.Context, basketID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSymbolBasketSymbols, basketID)
	return err
}

const getSymbolBasket = `-- name: GetSymbolBasket :one
SELECT id, user_id, name, created_at, updated_at FROM symbol_baskets
WHERE id = $1 AND user_id = $2
`

type GetSymbolBasketParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSymbolBasket(ctx context.Context, arg GetSymbolBasketParams) (SymbolBasket, error) {
	row := q.db.QueryRow(ctx, getSymbolBasket, arg.ID, arg.UserID)
	var i SymbolBasket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSymbolBasketMembers = `-- name: ListSymbolBasketMembers :many
SELECT bs.basket_id, bs.ord, s.id, s.ticker, s.short_name, s.long_name, s.kind, s.currency, s.lot_size, s.tick_size, s.point_value, s.active, s.tracked, s.first_seen, s.last_seen, s.created_at, s.updated_at
FROM symbol_basket_symbols bs
JOIN symbols s ON s.id = bs.symbol_id
WHERE bs.basket_id = ANY($1::uuid[])
ORDER BY bs.basket_id, bs.ord
`

type ListSymbolBasketMembersRow struct {
	BasketID   uuid.UUID  `json:"basket_id"`
	Ord        int32      `json:"ord"`
	ID         int64      `json:"id"`
	Ticker     string     `json:"ticker"`
	ShortName  *string    `json:"short_name"`
	LongName   *string    `json:"long_name"`
	Kind       string     `json:"kind"`
	Currency   string     `json:"currency"`
	LotSize    int32      `json:"lot_size"`
	TickSize   float64    `json:"tick_size"`
	PointValue *float64   `json:"point_value"`
	Active     bool       `json:"active"`
	Tracked    bool       `json:"tracked"`
	FirstSeen  *time.Time `json:"first_seen"`
	LastSeen   *time.Time `json:"last_seen"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

func (q *Queries) ListSymbolBasketMembers(ctx context.Context, dollar_1 []uuid.UUID) ([]ListSymbolBasketMembersRow, error) {
	rows, err := q.db.Query(ctx, listSymbolBasketMembers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSymbolBasketMembersRow{}
	for rows.Next() {
		var i ListSymbolBasketMembersRow
		if err := rows.Scan(
			&i.BasketID,
			&i.Ord,
			&i.ID,
			&i.Ticker,
			&i.ShortName,
			&i.LongName,
			&i.Kind,
			&i.Currency,
			&i.LotSize,
			&i.TickSize,
			&i.PointValue,
			&i.Active,
			&i.Tracked,
			&i.FirstSeen,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSymbolBaskets = `-- name: ListSymbolBaskets :many
SELECT id, user_id, name, created_at, updated_at FROM symbol_baskets
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListSymbolBaskets(ctx context.Context, userID uuid.UUID) ([]SymbolBasket, error) {
	rows, err := q.db.Query(ctx, listSymbolBaskets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymbolBasket{}
	for rows.Next() {
		var i SymbolBasket
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSymbolBasket = `-- name: UpdateSymbolBasket :one
UPDATE symbol_baskets
SET name = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, created_at, updated_at
`

type UpdateSymbolBasketParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) UpdateSymbolBasket(ctx context.Context, arg UpdateSymbolBasketParams) (SymbolBasket, error) {
	row := q.db.QueryRow(ctx, updateSymbolBasket, arg.ID, arg.UserID, arg.Name)
	var i SymbolBasket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
