// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: symbols.sql

package database

import (
	"context"
	"time"
)

const deactivateSymbols = `-- name: DeactivateSymbols :many
UPDATE symbols
SET active = FALSE, updated_at = NOW()
WHERE active AND ticker = ANY($1::text[])
RETURNING ticker
`

func (q *Queries) DeactivateSymbols(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, deactivateSymbols, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var ticker string
		if err := rows.Scan(&ticker); err != nil {
			return nil, err
		}
		items = append(items, ticker)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSymbolByTicker = `-- name: GetSymbolByTicker :one
SELECT id, ticker, short_name, long_name, kind, currency, lot_size, tick_size, point_value, active, tracked, first_seen, last_seen, created_at, updated_at FROM symbols WHERE ticker = $1
`

func (q *Queries) GetSymbolByTicker(ctx context.Context, ticker string) (Symbol, error) {
	row := q.db.QueryRow(ctx, getSymbolByTicker, ticker)
	var i Symbol
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.ShortName,
		&i.LongName,
		&i.Kind,
		&i.Currency,
		&i.LotSize,
		&i.TickSize,
		&i.PointValue,
		&i.Active,
		&i.Tracked,
		&i.FirstSeen,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSymbols = `-- name: ListSymbols :many
SELECT id, ticker, short_name, long_name, kind, currency, lot_size, tick_size, point_value, active, tracked, first_seen, last_seen, created_at, updated_at FROM symbols ORDER BY ticker
`

func (q *Queries) ListSymbols(ctx context.Context) ([]Symbol, error) {
	rows, err := q.db.Query(ctx, listSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Symbol{}
	for rows.Next() {
		var i Symbol
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.ShortName,
			&i.LongName,
			&i.Kind,
			&i.Currency,
			&i.LotSize,
			&i.TickSize,
			&i.PointValue,
			&i.Active,
			&i.Tracked,
			&i.FirstSeen,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackedSymbols = `-- name: ListTrackedSymbols :many
SELECT id, ticker, short_name, long_name, kind, currency, lot_size, tick_size, point_value, active, tracked, first_seen, last_seen, created_at, updated_at FROM symbols WHERE tracked ORDER BY ticker
`

func (q *Queries) ListTrackedSymbols(ctx context.Context) ([]Symbol, error) {
	rows, err := q.db.Query(ctx, listTrackedSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Symbol{}
	for rows.Next() {
		var i Symbol
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.ShortName,
			&i.LongName,
			&i.Kind,
			&i.Currency,
			&i.LotSize,
			&i.TickSize,
			&i.PointValue,
			&i.Active,
			&i.Tracked,
			&i.FirstSeen,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSymbol = `-- name: UpsertSymbol :one
INSERT INTO symbols (
    ticker, short_name, long_name, kind, currency,
    lot_size, tick_size, point_value, active, tracked,
    first_seen, last_seen
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12
)
ON CONFLICT (ticker) DO UPDATE SET
    short_name  = COALESCE(EXCLUDED.short_name, symbols.short_name),
    long_name   = COALESCE(EXCLUDED.long_name, symbols.long_name),
    kind        = EXCLUDED.kind,
    currency    = EXCLUDED.currency,
    lot_size    = EXCLUDED.lot_size,
    tick_size   = EXCLUDED.tick_size,
    point_value = COALESCE(EXCLUDED.point_value, symbols.point_value),
    active      = EXCLUDED.active,
    tracked     = symbols.tracked OR EXCLUDED.tracked,
    first_seen  = LEAST(symbols.first_seen, EXCLUDED.first_seen),
    last_seen   = GREATEST(symbols.last_seen, EXCLUDED.last_seen),
    updated_at  = NOW()
RETURNING id, ticker, short_name, long_name, kind, currency, lot_size, tick_size, point_value, active, tracked, first_seen, last_seen, created_at, updated_at
`

type UpsertSymbolParams struct {
	Ticker     string     `json:"ticker"`
	ShortName  *string    `json:"short_name"`
	LongName   *string    `json:"long_name"`
	Kind       string     `json:"kind"`
	Currency   string     `json:"currency"`
	LotSize    int32      `json:"lot_size"`
	TickSize   float64    `json:"tick_size"`
	PointValue *float64   `json:"point_value"`
	Active     bool       `json:"active"`
	Tracked    bool       `json:"tracked"`
	FirstSeen  *time.Time `json:"first_seen"`
	LastSeen   *time.Time `json:"last_seen"`
}

func (q *Queries) UpsertSymbol(ctx context.Context, arg UpsertSymbolParams) (Symbol, error) {
	row := q.db.QueryRow(ctx, upsertSymbol,
		arg.Ticker,
		arg.ShortName,
		arg.LongName,
		arg.Kind,
		arg.Currency,
		arg.LotSize,
		arg.TickSize,
		arg.PointValue,
		arg.Active,
		arg.Tracked,
		arg.FirstSeen,
		arg.LastSeen,
	)
	var i Symbol
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.ShortName,
		&i.LongName,
		&i.Kind,
		&i.Currency,
		&i.LotSize,
		&i.TickSize,
		&i.PointValue,
		&i.Active,
		&i.Tracked,
		&i.FirstSeen,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
